title: "My Website"
description: "Example website"

url: "https://n-leo.github.io"
baseurl: "/skills-github-pages"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

footer:
  links: []

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false

markdown: kramdown

include:
  - _pages
